var msg={username:'',password:'',login_result:'',role:'',confirm_password:'',email:'',regi_fail_reason:''}
                            var myvue=new Vue(
                              {
                                el:"#loginDiv",
                                data:msg,
                                http:{
                                  root:'192.168.1.129/',
                                },
                                methods:{
                                  submit:function(){
                                    this.$http.post(('frontpage.html/login_request'),{username:msg.username,password:msg.password},{emlateJSON:false}).then(
                                    response=>{
                                      this.grouplist=response.body;
                                      msg.login_result=response.body.login_result
                                      msg.role=response.body.role
                                      console.log(response.body)
                                    },respose=>{
                                      consle.log(respose);
                                      alter("Fail")
                                    }
                                    );
                                  },
                                  login_out:function(){
                                    msg.login_result=''
                                    msg.username=''
                                    msg.password=''
                                  },
                                  register:function(){
                                    msg.login_result='regi'
                                    msg.regi_fail_reason=''
                                    msg.username=''
                                    msg.password=''
                                  },
                                  confirm_register:function(){
                                    var regexp_mail= /^([a-zA-Z]|[0-9])(\w|\-)+@[a-zA-Z0-9]+\.([a-zA-Z]{2,4})$/;
                                    var commit_flag=0;//当commit_flag为0的时候处于本地验证，为1发送到服务器
                                    if(msg.username==""||msg.password==""){
                                        msg.regi_fail_reason='用户名或密码为空'
                                    }else if(msg.password != msg.confirm_password){
                                        msg.regi_fail_reason='密码和确认密码不一致'
                                    }else if(!regexp_mail.test(msg.email)){
                                       msg.regi_fail_reason='邮箱格式不正确'
                                    }else{
                                        regexp_flag=1
                                    }
                                    if(regexp_flag==1){
                                        this.$http.post(('frontpage.html/login_register'),{username:msg.username,password:msg.password,email:msg.email},{emlateJSON:false}).then(
                                            response=>{
                                                this.grouplist=response.body;
                                                msg.regi_fail_reason=response.body.regi_fail_reason
                                                if(msg.regi_fail_reason=='succ'){
                                                    msg.username=''
                                                    msg.password=''
                                                    msg.email=''
                                                    setTimeout(function(){
                                                        msg.login_result=''
                                                        },2000
                                                    )
                                                }
                                                console.log(response.body)
                                            },respose=>{
                                                consle.log(respose);
                                                alter("Fail")
                                            }
                                        );
                                    }
                                  }
                                }
                              }
                            )